stages:
  - quality
  - security

quality:
  stage: quality
  image: python:3.11

  before_script:
    - pip install -r requirements-dev.txt

  script:
    - bandit -r backend
    - pylint backend
    - flake8 .
    - semgrep --config .semgrep.yml .

gitleaks_secret_scanning:
  stage: security
  image:
    name: zricethezav/gitleaks:v8.21.2
    entrypoint: [""]

  script:
    - gitleaks detect --source . --config .gitleaks.toml --redact

pip_audit_dependency_audit:
  stage: security
  image: python:3.11

  before_script:
    - pip install -r requirements-dev.txt

  script:
    - pip-audit